#!/bin/bash

set -eu -o pipefail

FILE_PATH="$(basename "$1")"
FILE_NAME="${FILE_PATH%.*}"

inkscape \
  --export-type=png \
  --export-page=1-27 \
  --export-background-opacity=0 \
  --export-width=800 \
  "$FILE_PATH"
  
# -delay 10 — given 27 frames (27 Inkscape pages in SVG file), delay 10 makes it look like ~30fps
convert \
  -delay 10 \
  -loop 0 \
  "${FILE_NAME}_p"{1..27}.png "${FILE_NAME}.gif"

rm ./*.png

printf 'Done.\n'
ls --size --human-readable "${FILE_NAME}.gif"