#!/bin/bash

set -eu -o pipefail

FILE_PATH="$1"
FILE_NAME="$(basename "$1")"
NAME="${FILE_NAME%.*}"
DIR_NAME="$(dirname "$FILE_PATH")"

inkscape \
  --export-type=png \
  --export-page=1-24 \
  --export-background-opacity=0 \
  --export-width=800 \
  "$FILE_PATH"
  
# -delay 10 — given 27 frames (27 Inkscape pages in SVG file), delay 10 makes it look like ~30fps
convert \
  -delay 10 \
  -loop 0 \
  "${DIR_NAME}/${NAME}_p"{1..24}.png "${DIR_NAME}/${NAME}.gif"

rm "${DIR_NAME}"/*.png

printf 'Done.\n'
ls --size --human-readable "${DIR_NAME}/${NAME}.gif"