#!/bin/bash

FILE_NAME="$(basename -- $1)"
EXTENSION="${FILE_NAME##*.}"
NAME="${FILE_NAME%.*}"

D="$(convert "$1" -format "%[fx:w<h?w:h]" info:)"
convert "$1" -gravity center -extent "${D}x${D}" "./${NAME}_${D}x${D}.$EXTENSION"
