#!/bin/bash

#
# DESCRIPTION
#     Removes old revisions of snaps
# 
# NOTES
#     - close all snaps before running this
#

set -eu -o pipefail

printf 'Removing old snaps...\n'

LANG=C snap list --all | \
  awk '/disabled/{print $1, $3}' | \
  while read -r snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done
  
printf 'Done\n'
