#!/bin/bash

#
# DESCRIPTION
#     Removes all configuration files left after removal of packages
#

# If this script runs as a cron job and doesn't find anything to purge, it will return an error and cron job will fail. To prevent this we supress error output by sending it to /dev/null

set -eu -o pipefail
# printenv

printf 'Removing config files of all removed packages...\n'

dpkg -l | \
  grep '^rc' | \
  awk '{print $2}' | \
  sudo xargs --no-run-if-empty dpkg --purge

printf '\nDone\n'
