#!/bin/bash

WIDTH="${1:-500}"
HEIGHT="${2:-500}"

mkdir --parent "$PWD/resized"
mogrify \
  -resize "${WIDTH}x${HEIGHT}" \
  -gravity center \
  -transparent white \
  -density 300 \
  -quality 100 \
  -path ./resized "$PWD/*.jpg"
