#!/bin/bash

WIDTH="$1"
HEIGHT="$2"

mkdir ./resized
mogrify \
  -resize "${WIDTH}x${HEIGHT}" \
  -gravity center \
  -extent "$(expr "$WIDTH" + 100)x$(expr "$HEIGHT" + 100)" \
  -density 300 \
  -quality 100 \
  -path ./resized ./*.jpg