#!/bin/bash

# ###################################################################
# Removes old revisions of snaps
# ###################################################################
#
# How to use:
# - close all snaps before running this
#
#####################################################################

set -eu

LANG=C snap list --all | awk '/disabled/{print $1, $3}' |
  while read snapname revision; do
    snap remove "$snapname" --revision="$revision"
  done
