#!/bin/bash

# DESCRIPTION
#   Splits FLAC, APE or WV using CUE sheet. 
#   If the file is not FLAC, it also converts it to FLAC. The script also
#   copies ID3v2 metadata from CUE sheet to each audio file.
#
# SYNTAX 
#   - to split audio file using CUE sheet: 
#     <FLAC filename or full path> <CUE filename or full path>
#   - example: ./script Pete Namlook & Dr. Atmo ‎– Silence.flac \
#                       Pete Namlook & Dr. Atmo ‎– Silence.cue
#
# NOTES
#   - concerning the subject of quality loss while ecoding/decoding
#     https://superuser.com/questions/447338/understanding-conversion-and-decompression-of-lossless-audio

check_dependencies () {
  dependencies=( "ffmpeg" "iconv" "shnsplit" "flac" "cuetag" )

  for dependency in "${dependencies[@]}"
  do
    if ! command -v "$dependency" &> /dev/null
    then 
      printf "\n%s required.\n" "$dependency"
      exit 1
    fi
  done
}

split_flac () {
  printf "\n*** Split FLAC ***\n"

  printf "\n- Split audio file using CUE sheet\n"
  printf "%s.flac\n" "$AUDIO_NAME"
  shnsplit \
    -f "$CUE_PATH" \
    -t "%n. %p - %t" \
    -o flac \
    "$AUDIO_NAME.flac"
  
  printf "\n- Copy ID3v2 tags from CUE sheet to each audio file\n"
  cuetag "$CUE_PATH" [[:digit:]]*.flac
}

convert_to_flac () {
  printf "\n*** Convert source audio to FLAC ***\n"

  # `shnsplit` can convert APE to FLAC directly, but that requires us to 
  # install extra package - APE codec 
  # (https://github.com/fernandotcl/monkeys-audio). 
  # So instead of using `shnsplit` at this step I just use `ffmpeg` and `flac`.

  printf "\n- Convert to WAV\n"
  ffmpeg \
    -hide_banner \
    -loglevel error \
    -i "$AUDIO_BASENAME" "$AUDIO_NAME.wav"

  printf "\n- Convert WAV to FLAC\n"
  flac ./*.wav

  printf "\n- Delete intermediate WAV file\n"
  rm --verbose "$AUDIO_NAME.wav"
}

process_audio () {
  case "$AUDIO_EXTENSION" in
    "flac" )
      split_flac
      ;;
    "wv" | "ape" )
      convert_to_flac
      split_flac
      printf "\n- Delete intermediate FLAC file\n"
      rm --verbose "$AUDIO_NAME.flac"
      ;;
    * )
      printf "\nUnsupported audio format :(\n"
      exit 1
  esac

  read -rp $'\nDo you want to delete _source_ file? [Yy/Nn] '
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    rm --verbose "$AUDIO_BASENAME"
  fi

  echo -e "\nDone!"
}

set -eu -o pipefail
clear

check_dependencies

AUDIO_PATH="$1"
CUE_PATH="$2"
AUDIO_BASENAME="$(basename -- "$AUDIO_PATH")"
AUDIO_EXTENSION="${AUDIO_BASENAME##*.}"
AUDIO_NAME="${AUDIO_BASENAME%.*}"

process_audio
