#!/bin/bash

# OBS - Open Broadcaster Software (video Streaming, screencasting)

# Install
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update
sudo apt install obs-studio
obs --version

# Uninstall
sudo apt remove obs-studio
