#!/bin/bash

set -eu -o pipefail

TOKEN="$1"

curl \
  --request GET \
  --header 'Content-Type: application/json' \
  --header "Authorization: Bearer $TOKEN" \
  'https://api.simplecloud.ru/v3/vps?page=1&per_page=10'
