#!/bin/bash

set -eu -o pipefail

printf '\n##\n##\tRUNNING WITH ENVIRONMENT=\"%s\"\n##\n\n' "$NODE_ENV"

printf 'Start app...\n'

if [[ "${NODE_ENV}" == 'test' ]]
then
	npm run serve:test
fi

if [[ "${NODE_ENV}" == 'development' ]]
then
  npm run serve:dev
fi

if [[ "${NODE_ENV}" == 'production' ]]
then
	npm run build
else
  printf 'Invalid argument. Allowed values are: "dev", "test", "prod"\n\n'
fi
